trigger:
- master  # Set the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo 'Installing dependencies...'
    npm install
  displayName: 'Install Dependencies'

- script: |
    echo 'Building React app...'
    npm run build
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'build'
    artifactName: 'drop'
  displayName: 'Publish Artifact'